// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FLATGEOBUF_FLATGEOBUF_H_
#define FLATBUFFERS_GENERATED_FLATGEOBUF_FLATGEOBUF_H_

#include "flatbuffers/flatbuffers.h"

#include "column_generated.h"
#include "feature_generated.h"
#include "geometry_generated.h"

namespace FlatGeobuf {

struct Header;

struct Header FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_NAME = 4,
    VT_ENVELOPE = 6,
    VT_GEOMETRY_TYPE = 8,
    VT_DIMENSIONS = 10,
    VT_COLUMNS = 12,
    VT_FEATURES_COUNT = 14,
    VT_INDEX_NODE_SIZE = 16,
    VT_INDEX_OFFSET_SIZE = 18,
    VT_SRS = 20,
    VT_SRS_ORG = 22,
    VT_HAS_FID = 24,
    VT_HAS_SRS = 26
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<double> *envelope() const {
    return GetPointer<const flatbuffers::Vector<double> *>(VT_ENVELOPE);
  }
  GeometryType geometry_type() const {
    return static_cast<GeometryType>(GetField<uint8_t>(VT_GEOMETRY_TYPE, 0));
  }
  uint8_t dimensions() const {
    return GetField<uint8_t>(VT_DIMENSIONS, 2);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Column>> *columns() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Column>> *>(VT_COLUMNS);
  }
  uint64_t features_count() const {
    return GetField<uint64_t>(VT_FEATURES_COUNT, 0);
  }
  uint16_t index_node_size() const {
    return GetField<uint16_t>(VT_INDEX_NODE_SIZE, 16);
  }
  uint8_t index_offset_size() const {
    return GetField<uint8_t>(VT_INDEX_OFFSET_SIZE, 4);
  }
  uint32_t srs() const {
    return GetField<uint32_t>(VT_SRS, 0);
  }
  const flatbuffers::String *srs_org() const {
    return GetPointer<const flatbuffers::String *>(VT_SRS_ORG);
  }
  bool has_fid() const {
    return GetField<uint8_t>(VT_HAS_FID, 1) != 0;
  }
  bool has_srs() const {
    return GetField<uint8_t>(VT_HAS_SRS, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_ENVELOPE) &&
           verifier.VerifyVector(envelope()) &&
           VerifyField<uint8_t>(verifier, VT_GEOMETRY_TYPE) &&
           VerifyField<uint8_t>(verifier, VT_DIMENSIONS) &&
           VerifyOffset(verifier, VT_COLUMNS) &&
           verifier.VerifyVector(columns()) &&
           verifier.VerifyVectorOfTables(columns()) &&
           VerifyField<uint64_t>(verifier, VT_FEATURES_COUNT) &&
           VerifyField<uint16_t>(verifier, VT_INDEX_NODE_SIZE) &&
           VerifyField<uint8_t>(verifier, VT_INDEX_OFFSET_SIZE) &&
           VerifyField<uint32_t>(verifier, VT_SRS) &&
           VerifyOffset(verifier, VT_SRS_ORG) &&
           verifier.VerifyString(srs_org()) &&
           VerifyField<uint8_t>(verifier, VT_HAS_FID) &&
           VerifyField<uint8_t>(verifier, VT_HAS_SRS) &&
           verifier.EndTable();
  }
};

struct HeaderBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Header::VT_NAME, name);
  }
  void add_envelope(flatbuffers::Offset<flatbuffers::Vector<double>> envelope) {
    fbb_.AddOffset(Header::VT_ENVELOPE, envelope);
  }
  void add_geometry_type(GeometryType geometry_type) {
    fbb_.AddElement<uint8_t>(Header::VT_GEOMETRY_TYPE, static_cast<uint8_t>(geometry_type), 0);
  }
  void add_dimensions(uint8_t dimensions) {
    fbb_.AddElement<uint8_t>(Header::VT_DIMENSIONS, dimensions, 2);
  }
  void add_columns(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Column>>> columns) {
    fbb_.AddOffset(Header::VT_COLUMNS, columns);
  }
  void add_features_count(uint64_t features_count) {
    fbb_.AddElement<uint64_t>(Header::VT_FEATURES_COUNT, features_count, 0);
  }
  void add_index_node_size(uint16_t index_node_size) {
    fbb_.AddElement<uint16_t>(Header::VT_INDEX_NODE_SIZE, index_node_size, 16);
  }
  void add_index_offset_size(uint8_t index_offset_size) {
    fbb_.AddElement<uint8_t>(Header::VT_INDEX_OFFSET_SIZE, index_offset_size, 4);
  }
  void add_srs(uint32_t srs) {
    fbb_.AddElement<uint32_t>(Header::VT_SRS, srs, 0);
  }
  void add_srs_org(flatbuffers::Offset<flatbuffers::String> srs_org) {
    fbb_.AddOffset(Header::VT_SRS_ORG, srs_org);
  }
  void add_has_fid(bool has_fid) {
    fbb_.AddElement<uint8_t>(Header::VT_HAS_FID, static_cast<uint8_t>(has_fid), 1);
  }
  void add_has_srs(bool has_srs) {
    fbb_.AddElement<uint8_t>(Header::VT_HAS_SRS, static_cast<uint8_t>(has_srs), 0);
  }
  explicit HeaderBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  HeaderBuilder &operator=(const HeaderBuilder &);
  flatbuffers::Offset<Header> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Header>(end);
    return o;
  }
};

inline flatbuffers::Offset<Header> CreateHeader(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<double>> envelope = 0,
    GeometryType geometry_type = GeometryType::Point,
    uint8_t dimensions = 2,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Column>>> columns = 0,
    uint64_t features_count = 0,
    uint16_t index_node_size = 16,
    uint8_t index_offset_size = 4,
    uint32_t srs = 0,
    flatbuffers::Offset<flatbuffers::String> srs_org = 0,
    bool has_fid = true,
    bool has_srs = false) {
  HeaderBuilder builder_(_fbb);
  builder_.add_features_count(features_count);
  builder_.add_srs_org(srs_org);
  builder_.add_srs(srs);
  builder_.add_columns(columns);
  builder_.add_envelope(envelope);
  builder_.add_name(name);
  builder_.add_index_node_size(index_node_size);
  builder_.add_has_srs(has_srs);
  builder_.add_has_fid(has_fid);
  builder_.add_index_offset_size(index_offset_size);
  builder_.add_dimensions(dimensions);
  builder_.add_geometry_type(geometry_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<Header> CreateHeaderDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<double> *envelope = nullptr,
    GeometryType geometry_type = GeometryType::Point,
    uint8_t dimensions = 2,
    const std::vector<flatbuffers::Offset<Column>> *columns = nullptr,
    uint64_t features_count = 0,
    uint16_t index_node_size = 16,
    uint8_t index_offset_size = 4,
    uint32_t srs = 0,
    const char *srs_org = nullptr,
    bool has_fid = true,
    bool has_srs = false) {
  return FlatGeobuf::CreateHeader(
      _fbb,
      name ? _fbb.CreateString(name) : 0,
      envelope ? _fbb.CreateVector<double>(*envelope) : 0,
      geometry_type,
      dimensions,
      columns ? _fbb.CreateVector<flatbuffers::Offset<Column>>(*columns) : 0,
      features_count,
      index_node_size,
      index_offset_size,
      srs,
      srs_org ? _fbb.CreateString(srs_org) : 0,
      has_fid,
      has_srs);
}

inline const FlatGeobuf::Header *GetHeader(const void *buf) {
  return flatbuffers::GetRoot<FlatGeobuf::Header>(buf);
}

inline const FlatGeobuf::Header *GetSizePrefixedHeader(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<FlatGeobuf::Header>(buf);
}

inline bool VerifyHeaderBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<FlatGeobuf::Header>(nullptr);
}

inline bool VerifySizePrefixedHeaderBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<FlatGeobuf::Header>(nullptr);
}

inline void FinishHeaderBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<FlatGeobuf::Header> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedHeaderBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<FlatGeobuf::Header> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FlatGeobuf

#endif  // FLATBUFFERS_GENERATED_FLATGEOBUF_FLATGEOBUF_H_
