# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[package]
name = "fgbutil"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }
flatgeobuf = { path = ".." }
geozero = "0.10.0"
