[package]
name = "fgbutil"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }
geozero = { version = "0.9.5", default-features = true }

[dependencies.flatgeobuf]
path = ".."

[workspace]
members = ["."]
