// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlatGeobuf

type GeometryType = byte
const (
	GeometryTypePoint GeometryType = 0
	GeometryTypeMultiPoint GeometryType = 1
	GeometryTypeLineString GeometryType = 2
	GeometryTypeMultiLineString GeometryType = 3
	GeometryTypePolygon GeometryType = 4
	GeometryTypeMultiPolygon GeometryType = 5
)

var EnumNamesGeometryType = map[GeometryType]string{
	GeometryTypePoint:"Point",
	GeometryTypeMultiPoint:"MultiPoint",
	GeometryTypeLineString:"LineString",
	GeometryTypeMultiLineString:"MultiLineString",
	GeometryTypePolygon:"Polygon",
	GeometryTypeMultiPolygon:"MultiPolygon",
}

