// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatGeobuf
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Column : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Column GetRootAsColumn(ByteBuffer _bb) { return GetRootAsColumn(_bb, new Column()); }
  public static Column GetRootAsColumn(ByteBuffer _bb, Column obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Column __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public FlatGeobuf.ColumnType Type { get { int o = __p.__offset(6); return o != 0 ? (FlatGeobuf.ColumnType)__p.bb.Get(o + __p.bb_pos) : FlatGeobuf.ColumnType.Byte; } }
  public string Title { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTitleBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTitleArray() { return __p.__vector_as_array<byte>(8); }
  public string Description { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetDescriptionBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetDescriptionArray() { return __p.__vector_as_array<byte>(10); }
  public int Width { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }
  public int Precision { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }
  public int Scale { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }
  public bool Nullable { get { int o = __p.__offset(18); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }
  public bool Unique { get { int o = __p.__offset(20); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool PrimaryKey { get { int o = __p.__offset(22); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string Metadata { get { int o = __p.__offset(24); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMetadataBytes() { return __p.__vector_as_span<byte>(24, 1); }
#else
  public ArraySegment<byte>? GetMetadataBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public byte[] GetMetadataArray() { return __p.__vector_as_array<byte>(24); }

  public static Offset<FlatGeobuf.Column> CreateColumn(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      FlatGeobuf.ColumnType type = FlatGeobuf.ColumnType.Byte,
      StringOffset titleOffset = default(StringOffset),
      StringOffset descriptionOffset = default(StringOffset),
      int width = -1,
      int precision = -1,
      int scale = -1,
      bool nullable = true,
      bool unique = false,
      bool primary_key = false,
      StringOffset metadataOffset = default(StringOffset)) {
    builder.StartTable(11);
    Column.AddMetadata(builder, metadataOffset);
    Column.AddScale(builder, scale);
    Column.AddPrecision(builder, precision);
    Column.AddWidth(builder, width);
    Column.AddDescription(builder, descriptionOffset);
    Column.AddTitle(builder, titleOffset);
    Column.AddName(builder, nameOffset);
    Column.AddPrimaryKey(builder, primary_key);
    Column.AddUnique(builder, unique);
    Column.AddNullable(builder, nullable);
    Column.AddType(builder, type);
    return Column.EndColumn(builder);
  }

  public static void StartColumn(FlatBufferBuilder builder) { builder.StartTable(11); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddType(FlatBufferBuilder builder, FlatGeobuf.ColumnType type) { builder.AddByte(1, (byte)type, 0); }
  public static void AddTitle(FlatBufferBuilder builder, StringOffset titleOffset) { builder.AddOffset(2, titleOffset.Value, 0); }
  public static void AddDescription(FlatBufferBuilder builder, StringOffset descriptionOffset) { builder.AddOffset(3, descriptionOffset.Value, 0); }
  public static void AddWidth(FlatBufferBuilder builder, int width) { builder.AddInt(4, width, -1); }
  public static void AddPrecision(FlatBufferBuilder builder, int precision) { builder.AddInt(5, precision, -1); }
  public static void AddScale(FlatBufferBuilder builder, int scale) { builder.AddInt(6, scale, -1); }
  public static void AddNullable(FlatBufferBuilder builder, bool nullable) { builder.AddBool(7, nullable, true); }
  public static void AddUnique(FlatBufferBuilder builder, bool unique) { builder.AddBool(8, unique, false); }
  public static void AddPrimaryKey(FlatBufferBuilder builder, bool primaryKey) { builder.AddBool(9, primaryKey, false); }
  public static void AddMetadata(FlatBufferBuilder builder, StringOffset metadataOffset) { builder.AddOffset(10, metadataOffset.Value, 0); }
  public static Offset<FlatGeobuf.Column> EndColumn(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // name
    return new Offset<FlatGeobuf.Column>(o);
  }
  public ColumnT UnPack() {
    var _o = new ColumnT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ColumnT _o) {
    _o.Name = this.Name;
    _o.Type = this.Type;
    _o.Title = this.Title;
    _o.Description = this.Description;
    _o.Width = this.Width;
    _o.Precision = this.Precision;
    _o.Scale = this.Scale;
    _o.Nullable = this.Nullable;
    _o.Unique = this.Unique;
    _o.PrimaryKey = this.PrimaryKey;
    _o.Metadata = this.Metadata;
  }
  public static Offset<FlatGeobuf.Column> Pack(FlatBufferBuilder builder, ColumnT _o) {
    if (_o == null) return default(Offset<FlatGeobuf.Column>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _title = _o.Title == null ? default(StringOffset) : builder.CreateString(_o.Title);
    var _description = _o.Description == null ? default(StringOffset) : builder.CreateString(_o.Description);
    var _metadata = _o.Metadata == null ? default(StringOffset) : builder.CreateString(_o.Metadata);
    return CreateColumn(
      builder,
      _name,
      _o.Type,
      _title,
      _description,
      _o.Width,
      _o.Precision,
      _o.Scale,
      _o.Nullable,
      _o.Unique,
      _o.PrimaryKey,
      _metadata);
  }
}

public class ColumnT
{
  public string Name { get; set; }
  public FlatGeobuf.ColumnType Type { get; set; }
  public string Title { get; set; }
  public string Description { get; set; }
  public int Width { get; set; }
  public int Precision { get; set; }
  public int Scale { get; set; }
  public bool Nullable { get; set; }
  public bool Unique { get; set; }
  public bool PrimaryKey { get; set; }
  public string Metadata { get; set; }

  public ColumnT() {
    this.Name = null;
    this.Type = FlatGeobuf.ColumnType.Byte;
    this.Title = null;
    this.Description = null;
    this.Width = -1;
    this.Precision = -1;
    this.Scale = -1;
    this.Nullable = true;
    this.Unique = false;
    this.PrimaryKey = false;
    this.Metadata = null;
  }
}


static public class ColumnVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, true)
      && verifier.VerifyField(tablePos, 6 /*Type*/, 1 /*FlatGeobuf.ColumnType*/, 1, false)
      && verifier.VerifyString(tablePos, 8 /*Title*/, false)
      && verifier.VerifyString(tablePos, 10 /*Description*/, false)
      && verifier.VerifyField(tablePos, 12 /*Width*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*Precision*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*Scale*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*Nullable*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 20 /*Unique*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 22 /*PrimaryKey*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 24 /*Metadata*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
