// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatGeobuf
{

public enum ColumnType : byte
{
 BYTE = 0,
 UBYTE = 1,
 BOOL = 2,
 SHORT = 3,
 USHOT = 4,
 INT = 5,
 UINT = 6,
 FLOAT = 7,
 LONG = 8,
 ULONG = 9,
 DOUBLE = 10,
 STRING = 11,
 JSON = 12,
};


}
