// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum GeometryType : byte
{
 Point = 0,
 MultiPoint = 1,
 LineString = 2,
 MultiLineString = 3,
 Polygon = 4,
 MultiPolygon = 5,
};

